const COMMENTED_BY = 'COMMENTED_BY';
const POST_CREATED_BY = 'POST_CREATED_BY';
const IS_FRIENDS_WITH = 'FRIENDS';
const LIKED_BY = 'LIKED_BY';
const COMMENTED_ON_POST = 'COMMENTED_ON_POST';
const CHAT_SENT_BY = 'CHAT_SENT_BY';
const CHAT_RECEIVED_BY = 'CHAT_RECEIVED_BY';
const TYPE_POST = 'POST';
const TYPE_COMMENT='COMMENT';

export { COMMENTED_BY, POST_CREATED_BY, IS_FRIENDS_WITH , LIKED_BY, COMMENTED_ON_POST,CHAT_SENT_BY,TYPE_POST,TYPE_COMMENT,
        CHAT_RECEIVED_BY };